const fs=require('fs'),path=require('path'),multer=require('multer');
const pool=require('../config/db');
const { canAccessLabReports, isInDoctorCareSet, patientFilter } = require('../utils/patientAccess');
const { writeAudit, withTransaction } = require('../utils/audit');
const { resolveEncounterForRecord } = require('../utils/encounters');
// Report files live outside any web root; they are only ever served by the authorised handlers below.
// LAB_REPORT_DIR lets the test suite use a throwaway directory.
const dir=path.resolve(process.env.LAB_REPORT_DIR||path.join(__dirname,'..','uploads','lab-reports'));fs.mkdirSync(dir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:dir,filename:(q,f,cb)=>cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(f.originalname).toLowerCase()}`)}),limits:{fileSize:10*1024*1024},fileFilter:(q,f,cb)=>{const ok=['application/pdf','image/png','image/jpeg'].includes(f.mimetype)&&['.pdf','.png','.jpg','.jpeg'].includes(path.extname(f.originalname).toLowerCase());cb(ok?null:new Error('Only PDF, PNG, and JPEG reports are allowed'),ok)}});
exports.uploadReport=upload.single('report');
const lab=(q,s)=>q.user.role==='LABORATORY'||(s.status(403).json({success:false,message:'Forbidden'}),false);
const docAuth=async(q,p)=>q.user.role!=='DOCTOR'||isInDoctorCareSet(q.user.doctor_id,p);
exports.getTests=async(q,s)=>{try{const[r]=await pool.execute('SELECT * FROM lab_tests');s.json({success:true,data:r})}catch(e){s.status(500).json({success:false,message:e.message})}};
exports.createOrder=async(q,s)=>{const c=await pool.getConnection();try{if(['LABORATORY','PHARMACY'].includes(q.user.role))return s.status(403).json({success:false,message:'Forbidden'});let{patient_id,doctor_id,test_id,tests,notes,encounter_id}=q.body,list=tests||(test_id?[{test_id}]:[]);if(!list.length)return s.status(400).json({success:false,message:'No tests provided'});if(q.user.role==='DOCTOR'&&(Number(doctor_id)!==Number(q.user.doctor_id)||!(await docAuth(q,patient_id))))return s.status(403).json({success:false,message:'Forbidden'});await c.beginTransaction();const enc=await resolveEncounterForRecord(c,{encounterId:encounter_id,patientId:patient_id,doctorId:doctor_id});let ids=[];for(const t of list){const[x]=await c.execute('INSERT INTO lab_orders (patient_id,doctor_id,test_id,order_date,status,notes,encounter_id) VALUES (?,?,?,NOW(),"ORDERED",?,?)',[patient_id,doctor_id,t.test_id,notes,enc]);ids.push(x.insertId)}await writeAudit(c,q,{action:'CREATE_LAB_ORDER',entityType:'lab_order',entityId:ids[0],patientId:patient_id,details:{order_ids:ids,test_ids:list.map(t=>Number(t.test_id)),encounter_id:enc}});await c.commit();s.status(201).json({success:true,data:{ids,id:ids[0]}})}catch(e){await c.rollback();s.status(e.status||500).json({success:false,message:e.message})}finally{c.release()}};
// Lab staff see every order; doctors and nurses only orders for their own patients.
exports.listOrders=async(q,s)=>{try{const f=patientFilter(q.user,'lab','o.patient_id');const[r]=await pool.query(`SELECT o.*,p.name patient_name,t.name test_name,t.unit,t.normal_range,d.name doctor_name,lr.result_id FROM lab_orders o JOIN patients p ON p.patient_id=o.patient_id JOIN lab_tests t ON t.test_id=o.test_id JOIN doctors d ON d.doctor_id=o.doctor_id LEFT JOIN lab_results lr ON lr.order_id=o.order_id${f?` WHERE ${f.sql}`:''} ORDER BY o.order_date DESC`,f?f.params:[]);s.json({success:true,data:r})}catch(e){s.status(e.status||500).json({success:false,message:e.message})}};
exports.updateOrderStatus=async(q,s)=>{try{if(!lab(q,s))return;if(q.body.status!=='PROCESSING')return s.status(400).json({success:false,message:'Only PROCESSING is allowed'});const r=await withTransaction(q,async(c,audit)=>{const[u]=await c.execute('UPDATE lab_orders SET status="PROCESSING" WHERE order_id=? AND status="ORDERED"',[q.params.id]);if(u.affectedRows){const[[o]]=await c.execute('SELECT patient_id FROM lab_orders WHERE order_id=?',[q.params.id]);await audit({action:'UPDATE_LAB_ORDER_STATUS',entityType:'lab_order',entityId:q.params.id,patientId:o.patient_id,details:{from:'ORDERED',to:'PROCESSING'}})}return u});if(!r.affectedRows)return s.status(409).json({success:false,message:'Order is not available for processing'});s.json({success:true})}catch(e){s.status(500).json({success:false,message:e.message})}};
exports.addResult=async(q,s)=>{const c=await pool.getConnection();try{if(!lab(q,s))return;const{order_id,result_value,unit,reference_range,interpretation,technician_notes}=q.body;await c.beginTransaction();const[[o]]=await c.execute('SELECT order_id,patient_id FROM lab_orders WHERE order_id=? AND status="PROCESSING" FOR UPDATE',[order_id]);if(!o){await c.rollback();return s.status(409).json({success:false,message:'Order must be PROCESSING'})}const[r]=await c.execute('INSERT INTO lab_results (order_id,result_value,unit,reference_range,interpretation,technician_notes,performed_by,result_date) VALUES (?,?,?,?,?,?,?,NOW())',[order_id,result_value,unit||null,reference_range||null,interpretation||null,technician_notes||null,q.user.user_id]);await c.execute('UPDATE lab_orders SET status="COMPLETED" WHERE order_id=?',[order_id]);await writeAudit(c,q,{action:'RECORD_LAB_RESULT',entityType:'lab_result',entityId:r.insertId,patientId:o.patient_id,details:{order_id:Number(order_id),order_status:{from:'PROCESSING',to:'COMPLETED'},interpretation:interpretation||null}});await c.commit();s.status(201).json({success:true,data:{id:r.insertId}})}catch(e){await c.rollback();s.status(500).json({success:false,message:e.message})}finally{c.release()}};
const isId=v=>/^[1-9]\d{0,9}$/.test(String(v));
const REPORT_FORBIDDEN={success:false,message:'Forbidden: lab results are available only to laboratory staff and the patient\'s own doctors and nurses'};
// Streams one attachment row's file. The stored filename comes from the database, but the resolved
// path is still required to stay inside the report directory (no ../ or absolute-path escapes).
const sendReport=(s,a)=>{
  const file=path.resolve(dir,a.stored_filename);
  if(!file.startsWith(dir+path.sep))return s.status(400).json({success:false,message:'Invalid report path'});
  fs.stat(file,(err,st)=>{
    if(err||!st.isFile())return s.status(404).json({success:false,message:'Report file not found'});
    s.attachment(a.original_filename);s.type(a.mime_type);s.setHeader('Content-Length',st.size);s.setHeader('X-Content-Type-Options','nosniff');s.setHeader('Cache-Control','no-store');
    const stream=fs.createReadStream(file);
    stream.on('error',()=>{if(!s.headersSent)s.status(500).json({success:false,message:'Unable to read report'});else s.destroy()});
    stream.pipe(s);
  });
};
exports.getResult=async(q,s)=>{try{if(!isId(q.params.orderId))return s.status(400).json({success:false,message:'Invalid order id'});const[[o]]=await pool.execute('SELECT patient_id FROM lab_orders WHERE order_id=?',[q.params.orderId]);if(!o)return s.status(404).json({success:false,message:'Lab order not found'});s.locals.auditPatientId=o.patient_id;if(!(await canAccessLabReports(q.user,o.patient_id)))return s.status(403).json(REPORT_FORBIDDEN);const[r]=await pool.execute('SELECT lr.*,u.username performed_by_name FROM lab_results lr LEFT JOIN users u ON u.user_id=lr.performed_by WHERE lr.order_id=?',[q.params.orderId]);const a=r[0]?(await pool.execute('SELECT attachment_id,original_filename,mime_type,file_size,uploaded_at FROM lab_result_attachments WHERE result_id=?',[r[0].result_id]))[0]:[];s.json({success:true,data:{result:r[0]||null,attachments:a}})}catch(e){s.status(500).json({success:false,message:e.message})}};
exports.saveAttachment=async(q,s)=>{try{if(!lab(q,s))return;if(!q.file)return s.status(400).json({success:false,message:'Report required'});const[[r]]=await pool.execute('SELECT lr.result_id,o.patient_id FROM lab_results lr JOIN lab_orders o ON o.order_id=lr.order_id WHERE lr.order_id=?',[q.params.orderId]);if(!r)return s.status(404).json({success:false,message:'Result not found'});await withTransaction(q,async(c,audit)=>{const[a]=await c.execute('INSERT INTO lab_result_attachments (result_id,original_filename,stored_filename,mime_type,file_size,uploaded_by) VALUES (?,?,?,?,?,?)',[r.result_id,q.file.originalname,q.file.filename,q.file.mimetype,q.file.size,q.user.user_id]);await audit({action:'UPLOAD_LAB_REPORT',entityType:'lab_result_attachment',entityId:a.insertId,patientId:r.patient_id,details:{result_id:r.result_id,mime_type:q.file.mimetype,file_size:q.file.size}})});s.status(201).json({success:true})}catch(e){if(q.file)fs.unlink(q.file.path,()=>{});s.status(500).json({success:false,message:e.message})}};
const ATTACHMENT_WITH_PATIENT='SELECT a.*,o.patient_id FROM lab_result_attachments a JOIN lab_results r ON r.result_id=a.result_id JOIN lab_orders o ON o.order_id=r.order_id';
exports.downloadAttachment=async(q,s)=>{try{if(!isId(q.params.id))return s.status(400).json({success:false,message:'Invalid attachment id'});const[[a]]=await pool.execute(`${ATTACHMENT_WITH_PATIENT} WHERE a.attachment_id=?`,[q.params.id]);if(!a)return s.status(404).json({success:false,message:'Not found'});s.locals.auditPatientId=a.patient_id;if(!(await canAccessLabReports(q.user,a.patient_id)))return s.status(403).json(REPORT_FORBIDDEN);sendReport(s,a)}catch(e){s.status(500).json({success:false,message:e.message})}};
// GET /api/lab/reports/:result_id/download[?attachment_id=] — the latest attachment of a result unless one is named.
exports.downloadReport=async(q,s)=>{try{const{result_id}=q.params,{attachment_id}=q.query;if(!isId(result_id)||(attachment_id!==undefined&&!isId(attachment_id)))return s.status(400).json({success:false,message:'Invalid report id'});const[[r]]=await pool.execute('SELECT o.patient_id FROM lab_results r JOIN lab_orders o ON o.order_id=r.order_id WHERE r.result_id=?',[result_id]);if(!r)return s.status(404).json({success:false,message:'Lab result not found'});s.locals.auditPatientId=r.patient_id;if(!(await canAccessLabReports(q.user,r.patient_id)))return s.status(403).json(REPORT_FORBIDDEN);const[[a]]=attachment_id!==undefined?await pool.execute(`${ATTACHMENT_WITH_PATIENT} WHERE a.result_id=? AND a.attachment_id=?`,[result_id,attachment_id]):await pool.execute(`${ATTACHMENT_WITH_PATIENT} WHERE a.result_id=? ORDER BY a.attachment_id DESC LIMIT 1`,[result_id]);if(!a)return s.status(404).json({success:false,message:'No report attached to this result'});sendReport(s,a)}catch(e){s.status(500).json({success:false,message:e.message})}};
