// No database password may be written into the repository: every connection reads its credentials
// from the environment (server/.env, which is git-ignored). Scans every tracked file.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const SELF = path.relative(ROOT, __filename);
const PLACEHOLDER = /^(|<[^>]*>|change[-_]?me[\w-]*|replace[-_]?me[\w-]*|your[-_][\w-]*|placeholder[\w-]*|x+|\*+)$/i;
// A value is a literal unless it is an environment reference ($VAR, "${VAR}", or \"$VAR\" inside a
// JSON string) or an obvious placeholder (<...>, change-me, ...).
const isLiteral = (v) => {
  if (v === undefined) return false;
  const bare = v.replace(/^(\\?["'])+|(\\?["'])+$/g, '');
  return !bare.startsWith('$') && !bare.startsWith('<') && !PLACEHOLDER.test(bare);
};

// Returns "line: rule" findings for one file's text.
function scan(text, file = '') {
  const found = [];
  const lines = text.split('\n');
  lines.forEach((line, i) => {
    const at = (rule) => found.push(`${file}:${i + 1} ${rule}`);
    let m;
    if ((m = line.match(/MYSQL_PWD\s*=\s*("[^"]*"|'[^']*'|[^\s;&]+)/)) && isLiteral(m[1])) at('MYSQL_PWD set to a literal');
    if (/IDENTIFIED\s+(WITH\s+\S+\s+)?BY\s+['"]/i.test(line)) at('IDENTIFIED BY a literal password');
    if ((m = line.match(/\b(DB_PASSWORD|DB_ADMIN_PASSWORD|MYSQL_PASSWORD|MYSQL_ROOT_PASSWORD)\s*[:=]\s*("[^"]*"|'[^']*'|[^\s#]*)/)) && !/process\.env|\$\{/.test(line) && isLiteral(m[2])) at(`${m[1]} set to a literal`);
    if (/\bmysql(dump|admin)?\b[^\n]*\s-p(?!\s|["']?\$|$)\S/.test(line)) at('mysql -p<password> on the command line');
    if (/mysql:\/\/[^:\s/]+:[^@\s$]+@/.test(line)) at('password in a mysql:// URL');
  });
  // password: '<literal>' inside a createConnection/createPool({...}) call.
  const re = /create(Connection|Pool)\s*\(\s*\{([\s\S]*?)\}\s*\)/g;
  let m;
  while ((m = re.exec(text))) {
    const pw = m[2].match(/password\s*:\s*(['"`])((?:(?!\1).)*)\1/);
    if (pw && !pw[2].includes('${')) found.push(`${file}:${text.slice(0, m.index).split('\n').length} literal password in create${m[1]}`);
  }
  return found;
}

test('no tracked file contains a database password', () => {
  const files = execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' }).split('\n')
    .filter(f => f && f !== SELF && !/(^|\/)node_modules\/|package-lock\.json$|\.(png|jpe?g|gif|pdf|ico|woff2?)$/i.test(f));
  const findings = files.flatMap(f => {
    const p = path.join(ROOT, f);
    return fs.existsSync(p) ? scan(fs.readFileSync(p, 'utf8'), f) : [];
  });
  assert.deepEqual(findings, []);
});

test('the scanner catches each kind of literal (and allows env references and placeholders)', () => {
  // Samples are assembled at run time so no literal sits in this file.
  const pw = ['Hunter', '2', 'Secret!'].join('');
  const bad = [
    `export MYSQL_PWD='${pw}' && mysql -u root`,
    `const c = mysql.createConnection({ host: 'x', user: 'root', ${'pass' + 'word'}: '${pw}' });`,
    `CREATE USER 'a'@'h' IDENTIFIED BY '${pw}';`,
    `DB_PASSWORD=${pw}`,
    `mysql -u root -p${pw} hospital_db`,
    `DATABASE_URL=mysql://root:${pw}@db:3306/hospital_db`,
  ];
  for (const sample of bad) assert.equal(scan(sample).length, 1, sample);
  const fine = [
    'export MYSQL_PWD="$DB_ADMIN_PASSWORD" && mysql -u "$DB_ADMIN_USER"',
    "mysql.createConnection({ user: process.env.DB_USER, password: process.env.DB_PASSWORD })",
    "CREATE USER 'hospital_app'@'127.0.0.1' IDENTIFIED BY RANDOM PASSWORD;",
    'DB_PASSWORD=', 'DB_PASSWORD=change-me', 'DB_PASSWORD=<generated by MySQL>', 'MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}',
    'mysql -u root -p < docs/mysql-app-user.sql',
  ];
  for (const sample of fine) assert.deepEqual(scan(sample), [], sample);
});

module.exports = { scan };
